version: 2

build-defaults: &build-defaults
  docker:
    - image: circleci/node:12.20.0

jobs:
  test:
    <<: *build-defaults
    steps:
      - checkout
      - restore_cache:
          key: &cache_key dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup
          command: |
            npm i
            cd demo
            npm i
      - run:
          name: Run Linter
          command: ./node_modules/tslint/bin/tslint --project tsconfig.tslint.json --force | tee /tmp/test && ! grep -q WARNING /tmp/test
      - run:
          name: Run Tests
          command: npm run test-all
      - run:
          name: Test Building development
          command: npm run build
      - run:
          name: Test Building demo
          command: npm run build-demo
      - save_cache:
          key: *cache_key
          paths:
            - ./node_modules

workflows:
  version: 2
  test:
      jobs:
        - test
